server:
 port: 8761
logging:
 config: classpath:log4j2.xml

eureka:
 server:
  enable-self-preservation: false
 instance:
  hostname: peer1
 client:
  registerWithEureka: false
  fetchRegistry: false
  healthcheck:
   enabled: true
security:
 basic:
  enabled: true
 user:
  name: root
  password: 123456